### ISSUE TITLE
blockquote.scss pseudo quotes

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#363]
`blockquote`: [The Block Quotation element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) should have quotes `before` and `after`.

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/2075#issuecomment-743446963_

**Comment by mattiapontonio** [comment]
https://css-tricks.com/snippets/css/simple-and-nice-blockquote-styling/

**Comment by schalkneethling** [comment]
Because we do not _always_ use these to quote text from a different source, we should not just add quotes by default. We can experiment with an additional utility class but, for right now this is not needed. Thank you for the suggestion @mattiapontonio 

With that said, we do need to keep something that matches the expected styling as demonstrated here:
https://github.com/mdn/yari/issues/2075#issue-762271517

**Comment by mattiapontonio** [comment]
Thanks @schalkneethling
