### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#445]
.

**Comment by schalkneethling** [comment]
Thank you for the "recommendation" 😸 @mattiapontonio.  We might need to step back and consider whether these badges add much value or, whether there is a better way to implement them.

**Comment by mattiapontonio** [comment]
If you merged my PR we would have created an easy inconsistency that would raise an alignment more easily instead of arguing too much about badges. I see it long ... but it's okay.

**Comment by mattiapontonio** [comment]
What do You think about style the Cell here?

**Comment by schalkneethling** [comment]
> What do You think about style the Cell and remove the badge here?
> 
> ```
> <td data-status="recommendation">recommendation</td>
> ```

That is something to explore, but I still wonder whether we need anything additional. We have the appropriate phrase/word so, we are not solely relying on color here. It seems anything else is just window dressing and not really needed.

The other very important aspect here is how the relevant tables are coded. We need to ensure that they are accessible so that there is a clear connection between the column's table header and the cell container the text.

**Comment by mattiapontonio** [comment]
All true but we must also think about the design, in this case being that string an enum, finding a finite number of colors to associate on a border out of 4 could be a justifiable commitment but yes you are right there are priorities of HTML first.
So is this issue closable? How do we define it?

**Comment by mattiapontonio** [comment]
@schalkneethling close?
