### ISSUE TITLE
Highlight external links with CSS

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/mdn-minimalist#458]
It used to be https://github.com/mdn/content/issues/1738#issuecomment-767402105 that external links got appended with an icon declaring that it will move you away from MDN
(think https://icons8.com/icons/set/external-link )

Can we get that back?

Could be as easy as `a:link:not([href^="https://developer.mozilla.org/"])`?
(Need to take into account links to absolute/relative paths and anchors next to it).

**Comment by peterbe** [comment]
I actually think it might make a lot more sense to do it in Yari. You do it *once* in the build and every user benefits. Adding more the CSS will make the CSS more complex and most importantly, something like `a:link:not([href^="/"])` isn't foolproof because it might pick up things like `<a href="https://developer.mozilla.org/en-US/docs/Foo">`.

**Comment by peterbe** [comment]
@schalkneethling Perhaps redirect towards https://github.com/mdn/yari/pull/2728

**Comment by Ryuno-Ki** [comment]
Nitpick: Could we have the icon after the link? (But still within `<a>`). That way, it „looks nicer”.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/2728

**Comment by peterbe** [comment]
> Nitpick: Could we have the icon after the link? (But still within `<a>`). That way, it „looks nicer”.

What do you think about this @schalkneethling ?
I quite like his idea. It seems more right to have it on the right :)
