### ISSUE TITLE
margin/spacing not quite right on multple-column index lists

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/mdn-minimalist#467]
See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout#css_properties, and the two sections below it.

There is a gap at the top of the first list item, and bottom item in the first column is far too close to the content underneath it.

The multi-column layout is applied to lists inside a `<div class="index">`, using the following rule:

```
.article .index {
    -webkit-columns: 300px;
    columns: 300px;
}
```

Just applying `margin-top: 0;` to the `<ul>` immediately makes things better, but I don't know if you want to have a look at the spacing a bit mroe beyond that.

**Comment by schalkneethling** [comment]
@chrisdavidmills Apologies for taking so long to respond. Indeed that is not good at all. Thing is, it is not really something that can be fixed here in minimalist.

It is the symptom of a larger problem(spoiler alert: fix coming soon). Because the main content can start with an array of possible elements, we made a call before to not use top margins but only bottom margins. This is then what is leading to this problem.


As you know from the layout change I proposed via Slack, we are going to move the `h1` into the main element which, among other benefits, allows us to confidently use top and bottom margins on elements such as second-level headings.

As a neat little side effect, that will fix this problem. So, that is really long way of saying:

1. Bare with me, this will be resolved soon
2. I am going to close this issue as soon as the above has landed in Yari

Thank you, Chris!

**Comment by chrisdavidmills** [comment]
@schalkneethling awesome, thanks for the detailed explanation! This all sounds good to me.

**Comment by schalkneethling** [comment]
I see these elements use a container with a class of `index`. I am going to open an issue on Yari to add some styling to that class. Essentially some bottom margin to the container. @chrisdavidmills @rachelandrew is it safe to assume that in all of these instances, the unordered list is contained in a container with a class of `index` as in the example page in https://github.com/mdn/mdn-minimalist/issues/467#issue-800193733

**Comment by schalkneethling** [comment]
Here is the issue in Yari: https://github.com/mdn/yari/issues/3911

**Comment by rachelandrew** [comment]
I've only seen it on things using the index class.

**Comment by schalkneethling** [comment]
> I've only seen it on things using the index class.

There is now a pull request to address this https://github.com/mdn/yari/pull/3912. Going to close this issue and will then auto close the issue in Yari once the pull request is approved and merged.
